<a href="https://colab.research.google.com/github/Kshitish8/prelytix-summer-internship-2026/blob/main/DAY_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data = np.array([15, 42, -3, 87, 12, 55, 0, 33])

pos_small = data[(data > 0) & (data < 50)]  # Vectorized logic bitwise AND
print(pos_small)                            # Output: [15, 42, 33]

neg_or_big = data[(data < 0) | (data > 80)] # Vectorized logic bitwise OR
print(neg_or_big)                           # Output: [-3, 87]

not_zero = data[~(data == 0)]               # Vectorized logic bitwise NOT inversion flag
print(not_zero)

[15 42 12 33]
[-3 87]
[15 42 -3 87 12 55 33]


In [ ]:
print(np.any(data < 0))            # True (Evaluates if single element matches threshold logic)
print(np.all(data > 0))            # False (Checks if complete population complies with logic checkpoint)
# print(np.all(data > 0, axis=0))  # Axis evaluations trace capability variant across 2D arrays

True
False


In [ ]:
idx = np.nonzero(data > 40)
print(idx)       # Generates coordinates tuple tracking matching item positions
print(data[idx]) # Output: [42, 87, 55]

(array([1, 3, 5]),)
[42 87 55]


In [ ]:
import numpy as np
scores = np.array([45, 82, 67, 55, 91, 38, 74])

# Basic if-else logic element replacement
clipped = np.where(scores >= 60, scores, 60)

# Nested np.where statement arrays tracking string replacement categories
labels = np.where(scores >= 80, 'Dist', np.where(scores >= 60, 'Merit', 'Pass'))
print(labels)

# Inline math scaling executions triggered via specific array mask evaluations
bonus = np.where(scores >= 80, scores * 1.1, scores)
print(bonus.astype(int))

# Multi-condition map list assignment using np.select
conds = [scores >= 80, scores >= 60, scores >= 40]
vals = ['A', 'B', 'C']
grades = np.select(conds, vals, default='D')
print(grades)

['Pass' 'Dist' 'Merit' 'Pass' 'Dist' 'Pass' 'Merit']
[ 45  90  67  55 100  38  74]
['C' 'A' 'B' 'C' 'A' 'D' 'B']


In [ ]:
import numpy as np
m = np.arange(25).reshape(5, 5)

# Pull entire target rows by index listing values
print(m[[0, 2, 4], :])

# Direct extraction of coordinate pairs
r = [0, 1, 2]
c = [4, 3, 2]
print(m[r, c]) # Yields explicit spatial diagonal points: [4, 8, 12]

# Bounding sub-matrix slice grouping intersection cross-products via np.ix_
rows = [0, 2]
cols = [1, 3]
sub = m[np.ix_(rows, cols)]
print(sub) # Outputs custom structural cross-product grid block

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
[ 4  8 12]
[[ 1  3]
 [11 13]]


In [ ]:
print(m[::-1, :]) # Inverts horizon arrays vertically upside down
print(m[:, ::-1]) # Flips the orientation lines from left to right

[[20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]]


In [ ]:
import numpy as np
col = np.array([[0], [10], [20]]) # Shape (3, 1)
row = np.array([1, 2, 3, 4])     # Shape (4,)
print(col + row)                  # Results in a matrix block output with dimensions shape parameters (3, 4)

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


In [ ]:
data = np.random.randint(1, 100, (4, 5)).astype(float)
row_means = data.mean(axis=1, keepdims=True) # Forces output to shape parameters layout (4, 1) instead of flat (4,)
centred = data - row_means
print(centred.mean(axis=1))                 # Validates that calculated rows balance right at 0 values

[-1.42108547e-15  2.84217094e-15 -1.42108547e-15 -2.84217094e-15]


In [ ]:
a = np.array([1, 2, 3])[:, np.newaxis] # Transform array parameters shape layout to (3, 1)
b = np.array([10, 20, 30, 40])         # Shape parameters layout (4,)
print(a * b)                           # Vectorized outer matrix block calculation execution via broadcasting

[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]]


In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Three interchangeable statements for matrix cross dot product calculations
print(np.dot(A, B))
print(A @ B)       # Shorthand notation symbol operator format
print(np.matmul(A, B))

# Scalar multiplication mapping values position by position independently
print(A * B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [ ]:
import numpy as np
A = np.array([[2., 1.], [1., 3.]])

# Matrix Inversion computation
Ai = np.linalg.inv(A)
print(A @ Ai) # Output maps out a standard identity matrix footprint block

# Determinant evaluations
print(np.linalg.det(A))

# Eigenvalues & Eigenvectors Extraction
vals, vecs = np.linalg.eig(A)
print(vals)
print(vecs)

# Linear Equations Systems Solver engine tracking (Solving Ax = b structural variables equations)
b = np.array([8., 13.])
x = np.linalg.solve(A, b)
print(x)
print(A @ x) # Check matching response maps directly back to check value vector variables b

# Array Norm extraction types
v = np.array([3., 4.])
print(np.linalg.norm(v))        # Euclidean L2 norm validation calculation (5.0 value summary)
print(np.linalg.norm(A, 'fro')) # Matrix structural trace Frobenius Norm properties summary

[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
5.000000000000001
[1.38196601 3.61803399]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
[2.2 3.6]
[ 8. 13.]
5.0
3.872983346207417


In [ ]:
import numpy as np
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

print(np.sort(arr))    # Generates a separate sorted copy array trace layout
arr.sort()             # Directly updates internal order tracking elements in-place
print(np.argsort(arr)) # Returns argument mapping index array tracking position realignments

# Structural multi-axis matrices sorting configurations
m = np.random.randint(1, 20, (3, 4))
print(np.sort(m, axis=1)) # Sorts items along internal rows boundaries mapping vectors
print(np.sort(m, axis=0)) # Sorts items along internal columns fields mapping vectors

[1 1 2 3 4 5 5 6 9]
[0 1 2 3 4 5 6 7 8]
[[ 3  4  9 14]
 [ 2 11 13 19]
 [12 13 16 19]]
[[13  3  4  2]
 [14 11 12  9]
 [16 19 19 13]]


In [ ]:
k = 3
top_idx = np.argsort(arr)[-k:][::-1]
print(arr[top_idx])

[9 6 5]


In [ ]:
arr = np.array([1, 1, 2, 3, 4, 4, 5])
vals, counts = np.unique(arr, return_counts=True)
print(vals, counts)

# Efficient Binary Search boundary matching tracking via searchsorted
print(np.searchsorted(arr, 3))

[1 2 3 4 5] [2 1 1 2 1]
3


In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

print(np.intersect1d(a, b)) # Identifies structural items intersection shared between datasets
print(np.union1d(a, b))     # Collects all distinct elements tracking combined listings
print(np.setdiff1d(a, b))   # Captures item parameters present uniquely inside dataset a
print(np.in1d(a, b))        # Generates validation matching lists mapping boolean values

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[False False  True  True  True]


/tmp/ipykernel_1144/3217490127.py:7: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a, b))        # Generates validation matching lists mapping boolean values


In [ ]:
import numpy as np

# 1. Base array setup
arr = np.arange(100).reshape(10, 10)

# 2. Saving/Loading single binary file
np.save('data.npy', arr)
loaded = np.load('data.npy')

# 3. Saving/Loading multiple arrays in a compressed archive
np.savez('multi.npz', arr1=arr, arr2=arr * 2)
f = np.load('multi.npz')
print("Archive shapes:", f['arr1'].shape, f['arr2'].shape)

# 4. Writing & reading a clean CSV format
np.savetxt('out.csv', arr, delimiter=',', fmt='%d')
clean_data = np.loadtxt('out.csv', delimiter=',', dtype=int)

# --- THE FIX: Create 'messy.csv' so it actually exists in your directory ---
with open('messy.csv', 'w') as file:
    file.write("id,math,science,english\n")  # Header row (to be skipped) [cite: 520, 523]
    file.write("1,85,,92\n")                 # Row with a missing value
    file.write("2,74,68,81\n")
    file.write("3,,90,78\n")                 # Row with another missing value

# 5. Advanced file reading (Now handles missing items without crashing!)
data = np.genfromtxt('messy.csv', delimiter=',', filling_values=0, skip_header=1)

print("\n--- Loaded Messy Data (with missing values filled as 0) ---")
print(data)

Archive shapes: (10, 10) (10, 10)

--- Loaded Messy Data (with missing values filled as 0) ---
[[ 1. 85.  0. 92.]
 [ 2. 74. 68. 81.]
 [ 3.  0. 90. 78.]]


In [ ]:
import numpy as np

# Combine horizontal profile arrays side by side inside structural matrix layout form
data = np.column_stack([np.arange(1, 11), np.random.randint(40, 100, (10, 3))]).astype(float)

# Splitting columns parameters directly into named subset variables
ids = data[:, 0]
math = data[:, 1]
science = data[:, 2] # FIXED: Simply use integer index 2
english = data[:, 3]

# Computing custom composite indexes and statistics summaries maps
avg = data[:, 1:4].mean(axis=1)
total = data[:, 1:4].sum(axis=1)

# Double argsort ranking sequence execution strategy tracking argument tracking locations order
rank = total.argsort()[::-1].argsort() + 1

# Extract pinpoint location parameters mapping exact maximum performance coordinates
best_sub = np.argmax(data[:, 1:4].mean(axis=0))
print("Best subject index:", best_sub)

Best subject index: 0


In [ ]:
import numpy as np, time
n = 3000000
a = np.random.rand(n)
b = np.random.rand(n)

# PERFORMANCE LOSS: Element structural list loop iteration processing
t = time.perf_counter()
c = [a[i] + b[i] for i in range(n)]
print(f"Loop: {time.perf_counter()-t:.3f}s")

# OPTIMAL EXECUTION: Hardware vectorization matrix computations channel pipeline
t = time.perf_counter()
c = a + b
print(f"NumPy: {time.perf_counter()-t:.4f}s")

Loop: 2.164s
NumPy: 0.0586s


In [ ]:
# Overwriting data structures directly using operational arithmetic signs assignment shorthand
a += b
np.add(a, b, out=a) # Routing mathematical product calculation trace to targeted pointer index variable

# Pre-allocating clean placeholder storage maps before pipeline runtime execution loops
result = np.empty(n)
np.multiply(a, b, out=result)

array([0.06519096, 0.6040384 , 0.73167583, ..., 1.37506623, 0.58645169,
       0.89662549])

In [ ]:
import numpy as np
A = np.random.rand(100, 200)
B = np.random.rand(200, 150)

# Classical Multi-axis Matrix Multiplication using Einstein loop formatting rules
C = np.einsum('ij,jk->ik', A, B) # Identical matrix response trace matching expression: A @ B

# Matrix Trace Calculation (Summation value profile tracing diagonal coordinates axis intersections)
M = np.random.rand(5, 5)
print(np.einsum('ii->', M)) # Identical operational tracking response matching statement: np.trace(M)

# Processing separate element row-by-row profile vector dot product executions across array layouts
a = np.random.rand(10, 4)
b = np.random.rand(10, 4)
print(np.einsum('ij,ij->i', a, b)) # Outputs 10 precise scalar dot values calculations entries listing

2.2992865555918227
[0.32933084 0.17986126 0.51946699 1.22188168 1.54910698 0.60255242
 0.92165149 0.61872339 0.69734041 0.8267968 ]
