<a href="https://colab.research.google.com/github/Kshitish8/prelytix-summer-internship-2026/blob/main/DAY_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

# Python list multiplication repeats the sequence elements
py_list = [1, 2, 3, 4, 5]
print(py_list * 2)  # Output: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

# NumPy array multiplication transforms internal elements values
np_arr = np.array([1, 2, 3, 4, 5])
print(np_arr * 2)   # Output: [2, 4, 6, 8, 10]

In [ ]:
n = 1000000
big_list = list(range(n))
t = time.time()
squared_list = [x**2 for x in big_list]
print(f"List: {time.time()-t:.4f}s")

big_arr = np.arange(n)
t = time.time()
squared_arr = big_arr**2
print(f"NumPy: {time.time()-t:.4f}s") # ~100x faster execution track

In [ ]:
import numpy as np
print(np.__version__)

print(np.pi)   # 3.14159265...
print(np.e)    # 2.71828182...
print(np.inf)  # Infinity
print(np.nan)  # Not a Number placeholder

In [ ]:
import numpy as np

# 1D single dimension vector creation
a = np.array([10, 20, 30, 40])
print(a)
print(type(a)) # <class 'numpy.ndarray'>

# 2D structural multi-row grid matrix creation
m = np.array([[1, 2, 3,4], [5, 6 ,7 ,8], [9, 10, 11, 12]])
print(m)

In [ ]:
b = np.array([1, 2, 3], dtype=float) # Instantiates as float64 values
c = np.array([1.5, 2.71], dtype=int) # Truncates precision to integers instantly
print(b.dtype, c.dtype)

In [ ]:
import numpy as np

np.zeros((3, 4))                      # Grid prefilled with 0.0 zeroes
np.ones((2, 3))                       # Grid prefilled with 1.0 ones
np.full((2, 2), 7)                    # Custom filling scalar matrix shortcut
np.eye(3)                             # Identity matrix square array generation
np.empty((2, 2))                      # Uninitialized placeholder memory (garbage values)

# Sequence range builders
np.arange(10)                         # Counts 0 up to 9
np.arange(0, 20, 3)                   # Custom step-based count sequence
np.linspace(0, 1, 5)                  # Evenly splits range matching target element counts
np.logspace(0, 2, 3)                  # Logarithmically scaled geometric bounds

# Random matrix distribution sampling
np.random.rand(3, 3)                  # Continuous uniform distributions range [0.0, 1.0)
np.random.randn(3, 3)                 # Standard normal distribution sample curve
np.random.randint(1, 10, size=(3, 3)) # Discrete integer matrix bounds

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a.shape)     # Structural dimensional shape layout tuple: (rows, cols)
print(a.ndim)      # Matrix axis depth count (2)
print(a.size)      # Aggregate element volume count (12)
print(a.dtype)     # Core bit allocation configuration encoding
print(a.itemsize)  # Memory footprint usage per single item (bytes)
print(a.nbytes)    # Combined complete array hardware memory footprint

# Casting array layout to smaller footprint type parameters
b = a.astype(np.float32)
print(b.dtype)     # float32 conversion track
print(b.nbytes)    # Cuts total memory trace in half

# Matrix transposition axis transformations
print(a.T.shape)   # Inverts spatial shape orientation axes

In [ ]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60])

print(a[0])    # Extracts head element
print(a[-1])   # Extracts tail element
print(a[1:4])  # Range subset boundaries capture
print(a[::2])  # Interval step jump sequence capture
print(a[::-1]) # Flips the sequence order backwards

# CRITICAL BEHAVIOR: standard slice subsets represent MEMORY VIEWS rather than unique duplicates
s = a[2:5]
s[0] = 99      # Mutating a view directly updates the primary source array structure!
print(a)       # Output array reflects the change: [10, 20, 99, 40, 50, 60]

# SAFE ISOLATION: Explicitly call .copy() to decouple memory addresses
c = a[2:5].copy()
c[0] = 0       # Modifications remain localized within separate array block
print(a)       # Primary array structure remains protected and intact

10
60
[20 30 40]
[10 30 50]
[60 50 40 30 20 10]
[10 20 99 40 50 60]
[10 20 99 40 50 60]


In [ ]:
import numpy as np
m = np.arange(1, 13).reshape(3, 4)

print(m[0, 2])      # Accesses an explicit single cell coordinate: [Row 0, Column 2]
print(m[1, :])      # Extracts horizontal index sequence across row index 1
print(m[:, 2])      # Captures individual vertical profile at column index 2
print(m[0:2, 1:3])  # Captures bounding regional multi-row sub-matrices blocks
print(m[-1, -1])    # Direct hook to terminal bottom-right corner value

In [ ]:
import numpy as np
a = np.array([15, 42, -3, 87, -12, 55])

mask = a > 0
print(mask)     # Boolean evaluation map list
print(a[mask])  # Pulls coordinates passing logic checklist filter rules

print(a[a > 40]) # Shorthand inline array mask conditional expression

# Using np.where to filter or replace elements contextually
print(np.where(a > 0, a, 0))           # Clips out or sets all negative indices to zero
print(np.where(a > 50, 'High', 'Low')) # Map labels array conversion tracking text strings

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)   # Vectorized addition matching matching positions
print(b - a)   # Vectorized subtraction tracking
print(a * b)   # Vectorized scalar element multiplication scaling
print(b / a)   # Standard floating precision division
print(b // a)  # Truncated floor integer division
print(b ** 3)  # Exponential power conversions
print(a ** 2)

In [ ]:
import numpy as np
a = np.array([1, 4, 9, 16])

print(np.sqrt(a))                          # Vector square root computation
print(np.square(a))                        # Vector power calculations scaling upwards
print(np.abs(np.array([-1, -2, 3])))       # Converts items into absolute positive traces
print(np.exp(np.array([0, 1, 2])))         # Base-e exponential power computations
print(np.log(a))                           # Natural log evaluation transformations
print(np.log2(a))                          # Base-2 log mapping conversions
print(np.log10(a))                         # Base-10 log mapping calculations
print(np.sin(np.linspace(0, np.pi, 5)))    # High speed vector trigonometric loops
print(np.ceil(np.array([1.2, 3.7])))       # Rounds floating fields upwards to ceiling boundaries
print(np.floor(np.array([1.9, 3.1])))      # Truncates precision downwards to baseline floor boundaries
print(np.round(np.array([1.56, 3.44]), 1)) # Specified precision digit rounding

In [ ]:
import numpy as np
m = np.array([[1, 2, 3], [4, 5, 6]])

print(m.sum())               # Aggregated global sum of all matrix coordinates combined
print(m.sum(axis=0))         # Column summaries (collapses vertical rows)
print(m.sum(axis=1))         # Row summaries (collapses horizontal channels)
print(m.mean())              # Mean average evaluation tracking
print(m.std())               # Standard deviation calculation trace metric
print(m.var())               # Variance calculation trace metric
print(m.min(), m.max())      # Boundary structural endpoints search tracking extrema
print(m.argmin(), m.argmax()) # Flattened axis target pointers pointing to extrema indices
print(np.cumsum(m, axis=1))  # Horizontal cumulative summation tracking updates
print(np.prod(m, axis=0))    # Column cross multi-value product calculations tracking

In [ ]:
import numpy as np

# Scalar broadcasting scales all items uniformly
a = np.array([1, 2, 3, 4])
print(a + 100)

# 1D Row Vector layout expands vertically to match a 2D matrix shape
m = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])
print(m + row)

# Column vector tracking scales its shape horizontally across column barriers
col = np.array([[100], [200]])
print(m + col)

In [ ]:
import numpy as np
a = np.arange(24)

# Modifying dimensions boundaries (Volume parameters footprint capacity must match precisely)
b = a.reshape(4, 6)
c = a.reshape(2, 3, 4) # Projects flat values sequence into a 3D grid layout
d = a.reshape(8, -1)   # Passing -1 prompts automatic structural shape calculation parsing

# Vector flattening mechanics
flat_view = b.ravel()   # Performance memory view track
flat_copy = b.flatten() # Isolated separate variable data allocation trace copy

# Inserting empty axis placeholder channels inside vectors
x = np.array([1, 2, 3])
print(x[:, np.newaxis]) # Transforms flat array shape structure into an explicit Column Vector layout
print(x[np.newaxis, :]) # Transforms flat array shape structure into an explicit Row Vector layout

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Combining configurations across distinct dimension channels
print(np.vstack([a, b]))              # Stacks grid elements vertically over row dimensions
print(np.hstack([a, b]))              # Stacks grid elements horizontally over column dimensions
print(np.concatenate([a, b], axis=0)) # Direct structural match to vertical stacking mechanics
print(np.concatenate([a, b], axis=1)) # Direct structural match to horizontal stacking mechanics
print(np.stack([a, b], axis=0))        # Combines blocks into a multi-layer array assembly

# Array segmentation mechanics
x = np.arange(12).reshape(4, 3)
parts_v = np.vsplit(x, 2) # Splits matrix cleanly across horizontal row vectors lines
parts_h = np.hsplit(x, 3) # Splits matrix cleanly across vertical column parameters checkpoints